name: "Update Flake Inputs"

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-title: "chore: Update Nix flake inputs"
          pr-body: |
            Automated update of Nix flake inputs.

            This PR was automatically created by the weekly flake update workflow.

            Please review the changes and merge if CI passes.
          pr-labels: |
            dependencies
            automated
